### ISSUE TITLE
Evelyn can add MUI to Binary Ninja #2431

### ISSUE THREAD

**Issue by sschriner** [trailofbits/MUI#1]
### What:

MUI exists as a Binary Ninja plugin that can be installed from the plugin manager

### Acceptance Criteria:

* ~Evelyn can open Binary Ninja, navigate to the plugin manager and find MUI listed and install~ (see #16)
* ~The plugin will automatically install Manticore upon installation from Binary Ninja plugin manager~ (see above)
* A menu for configuring MUI appears under the "Tools" menu
* Evelyn can do this on her Mac machine
* Evelyn can do this on her Linux machine

From: https://github.com/trailofbits/manticore/issues/2431

**Comment by psifertex** [comment]
This can probably be re-opened as #16 has been resolved upstream some time ago.
