### ISSUE TITLE
George would like sensible defaults so that he can run MUI with as little clicks as possible

### ISSUE THREAD

**Issue by sschriner** [trailofbits/MUI#29]
### What: 

George would like sensible defaults so that he can run MUI with as little clicks as possible

### Acceptance Criteria: 

* George can launch a UI 
* In the UI, he can launch a new Manticore project
* A configuration dialog pops up
* The configuration dialog has sensible defaults for all supported Manticore options
* The configuration dialog allows George to customize Manticore's input
* After clicking OK (without changing anything), Manticore runs
* After clicking OK (with changing Manticore's input), Manticore runs
* After clicking OK (with changing Manticore's input to an invalid value), a relevant error message is shown to George

**Comment by ekilmer** [comment]
closed in https://github.com/trailofbits/MUI-Ghidra/pull/2
